### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by nakatatsu77** [nakatatsu77/portfolio#23]
# 概要
GitHubProjectsにてissueとおおよその実装順を洗い出しました。
[ProjectsURL](https://github.com/users/nakatatsu77/projects/4/views/1)

### 1週間辺りの開発に向けられる時間
- 1週間あたり：25時間
- ストーリーポイントを１週間あたり10~12消化予定

### MVPリリースまで
- [ ] rails new
- [ ] デプロイ
- [ ] ヘッダー
- [ ] フッター
- [ ] トップページ
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] ログアウト機能
- [ ] 投稿機能
- [ ] 投稿一覧機能
- [ ] 投稿詳細機能
- [ ] 画像アップロード機能
- [ ] AIによる画像生成機能

### MVP後
- [ ] いいね機能
- [ ] コメント機能
- [ ] Xへのシェア機能
- [ ] ランキングページの実装

### MVPレビュー依頼予定日
予定日：2024年 11月 30日

上記レビューのほど、よろしくお願いいたします。

**Comment by kenchasonakai** [comment]
LGTMです！

パスワードリセットは無くてもユーザーは使うことが出来ると思うので、MVP後に回してもよいかもしれませんね

**Comment by nakatatsu77** [comment]
ありがとうございます！
MVP後に実装に変更したいと思います
